### ISSUE TITLE
add `rdp` open API specs

### ISSUE THREAD

**Issue by benjaminch** [Qovery/scaleway-api-rs#4]
Seems `RDP API specs` is not valid from openAPI generator stand point:

https://developers.scaleway.com/static/985b639541bd9c5d8ad1d46561ca76c3/scaleway.rdb.v1.Api.yml

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors:
        -attribute components.schemas.scaleway.std.TimeSeries.Point.items is missing
        -attribute components.schemas.scaleway.std.TimeSeries.Point.items is not of type `object`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:546)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

```

**Comment by remyleone** [comment]
How could this bug be reproduced?

**Comment by benjaminch** [comment]
Hello @remyleone !

Thank for reaching out.

You can reproduce this bug by:

Running https://editor.swagger.io/ on https://developers.scaleway.com/static/985b639541bd9c5d8ad1d46561ca76c3/scaleway.rdb.v1.Api.yml content
<img width="1723" alt="Screenshot 2021-07-05 at 11 02 07" src="https://user-images.githubusercontent.com/1393795/124446185-7b5a4d00-dd80-11eb-9d09-1c8771df5477.png">

You can also reproduce it running `generate_api.sh` after adding this very file to the `wget` and merging schema.

Let me know if you need further help.

**Comment by benjaminch** [comment]
Fixed with new provided version: https://developers.scaleway.com/static/991ccc31ec600bedad34d7e8382799ec/scaleway.rdb.v1.Api.yml

```
 spectral lint https://developers.scaleway.com/static/991ccc31ec600bedad34d7e8382799ec/scaleway.rdb.v1.Api.yml

https://developers.scaleway.com/static/991ccc31ec600bedad34d7e8382799ec/scaleway.rdb.v1.Api.yml
   2:6    warning  info-contact           Info object must have "contact" object.                        info
  1521:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}.get
  1521:9  warning  operation-tags         Operation must have non-empty "tags" array.                    paths./rdb/v1/regions/{region}.get
  1545:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/backups.get
 1627:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/backups.post
  1679:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/backups/{database_backup_id}.get
 1712:11  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/backups/{database_backup_id}.patch
 1763:12  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/backups/{database_backup_id}.delete
 1797:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/backups/{database_backup_id}/export.post
 1837:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/backups/{database_backup_id}/restore.post
  1893:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/database-engines.get
  1934:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances.get
 2018:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances.post
  2122:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}.get
 2155:11  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}.patch
 2223:12  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}.delete
  2257:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/acls.get
 2304:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/acls.post
  2351:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/acls.put
 2398:12  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/acls.delete
  2446:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/certificate.get
 2480:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/clone.post
  2531:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/databases.get
 2611:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/databases.post
 2657:12  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/databases/{name}.delete
  2694:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/logs.get
  2848:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/privileges.get
  2921:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/privileges.put
 2982:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/renew-certificate.post
 2982:10  warning  operation-tags         Operation must have non-empty "tags" array.                    paths./rdb/v1/regions/{region}/instances/{instance_id}/renew-certificate.post
 3013:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/settings.post
  3060:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/settings.put
 3107:12  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/settings.delete
 3155:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/snapshots.post
  3276:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/users.get
 3342:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/users.post
 3397:11  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/users/{name}.patch
 3455:12  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/instances/{instance_id}/users/{name}.delete
  3492:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/logs/{instance_log_id}.get
  3526:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/node-types.get
  3573:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/snapshots.get
  3656:9  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/snapshots/{snapshot_id}.get
 3689:11  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/snapshots/{snapshot_id}.patch
 3740:12  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/snapshots/{snapshot_id}.delete
 3774:10  warning  operation-description  Operation "description" must be present and non-empty string.  paths./rdb/v1/regions/{region}/snapshots/{snapshot_id}/create-instance.post

✖ 45 problems (0 errors, 45 warnings, 0 infos, 0 hints)

```
